#!/bin/bash 

# clear
source ~/MMX_Toolkit/bash/_config_functions.sh 
read_config
# show_config

echo ">>> clearing tmp folder"
ls -al $MTK_MMX_DIRECTORY/_system/_tmp
rm -r  $MTK_MMX_DIRECTORY/_system/_tmp/* 2> /dev/null
ls -al $MTK_MMX_DIRECTORY/_system/_tmp
echo ">>> tmp folder cleared"
