#!/bin/bash 

# clear
source ~/MMX_Toolkit/bash/_config_functions.sh 
read_config
# show_config

echo ">>> clearing output folder"
ls -al $MTK_MMX_DIRECTORY/_system/_RBVMax/output
rm -r  $MTK_MMX_DIRECTORY/_system/_RBVMax/output/* 2> /dev/null
ls -al $MTK_MMX_DIRECTORY/_system/_RBVMax/output
echo ">>> output folder cleared"
